// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/jorgechavezrnd/test_project/internal"
	"sync"
)

// Ensure, that BeerRepoMock does implement beerscli.BeerRepo.
// If this is not the case, regenerate this file with moq.
var _ beerscli.BeerRepo = &BeerRepoMock{}

// BeerRepoMock is a mock implementation of beerscli.BeerRepo.
//
//     func TestSomethingThatUsesBeerRepo(t *testing.T) {
//
//         // make and configure a mocked beerscli.BeerRepo
//         mockedBeerRepo := &BeerRepoMock{
//             GetBeersFunc: func() ([]beerscli.Beer, error) {
// 	               panic("mock out the GetBeers method")
//             },
//         }
//
//         // use mockedBeerRepo in code that requires beerscli.BeerRepo
//         // and then make assertions.
//
//     }
type BeerRepoMock struct {
	// GetBeersFunc mocks the GetBeers method.
	GetBeersFunc func() ([]beerscli.Beer, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetBeers holds details about calls to the GetBeers method.
		GetBeers []struct {
		}
	}
	lockGetBeers sync.RWMutex
}

// GetBeers calls GetBeersFunc.
func (mock *BeerRepoMock) GetBeers() ([]beerscli.Beer, error) {
	if mock.GetBeersFunc == nil {
		panic("BeerRepoMock.GetBeersFunc: method is nil but BeerRepo.GetBeers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetBeers.Lock()
	mock.calls.GetBeers = append(mock.calls.GetBeers, callInfo)
	mock.lockGetBeers.Unlock()
	return mock.GetBeersFunc()
}

// GetBeersCalls gets all the calls that were made to GetBeers.
// Check the length with:
//     len(mockedBeerRepo.GetBeersCalls())
func (mock *BeerRepoMock) GetBeersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetBeers.RLock()
	calls = mock.calls.GetBeers
	mock.lockGetBeers.RUnlock()
	return calls
}
